layout_spectrum: 0.5405653
typography_spectrum: 0.5676198
color:
  saturation: 0.8841931
  lightness: 0.9149182
  brandStrength: 0.633768
  rhythmicContrast: 0.7084498
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Ckvisuals
